version: "3.9"
services:
  pg-fgoapijp:
    image: groonga/pgroonga:latest-alpine-13-slim
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: fgoapijp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg-jp-data:/var/lib/postgresql/data
  pg-fgoapina:
    image: groonga/pgroonga:latest-alpine-13-slim
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: fgoapina
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg-na-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  pg-jp-data:
  pg-na-data:
