[tool.poetry]
name = "fgo-game-data-api"
version = "0.0.1"
description = "Provide raw and processed FGO game data"
authors = ["squaresmile <squaresmile@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.54.2"
uvicorn = "^0.11.5"
python-dotenv = "^0.13.0"
fuzzywuzzy = "^0.18.0"
python-Levenshtein = "^0.12.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.2"
mypy = "^0.770"
black = "^19.10b0"
pytest-xdist = "^1.32.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
