[tool.poetry]
name = "fgo-game-data-api"
version = "5.38.0"
description = "Provide raw and processed FGO game data"
authors = ["squaresmile <squaresmile@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.63.0"
uvicorn = {extras = ["standard"], version = "^0.13.3"}
python-dotenv = "^0.15.0"
fuzzywuzzy = "^0.18.0"
python-Levenshtein = "^0.12.1"
orjson = "^3.4.7"
aiofiles = "^0.6.0"
GitPython = "^3.1.12"
toml = "^0.10.2"
redis = "^3.5.3"
SQLAlchemy = {extras = ["postgresql"], version = "^1.3.22"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pylint = "^2.6.0"
mypy = "^0.800"
black = "^20.8b1"
pytest-xdist = "^2.1.0"
requests = "^2.25.1"
coverage = "^5.4"
fuzzywuzzy-stubs = "^0.0.1"
isort = "^5.7.0"
sqlalchemy-stubs = "^0.4"

[tool.isort]
line_length = 88
known_third_party = "orjson"
multi_line_output = 3
force_grid_wrap = 0
lines_after_imports = 2
combine_as_imports = true
include_trailing_comma = true

[tool.pylint.MASTER]
extension-pkg-whitelist = "orjson,pydantic"

[tool.pylint.'MESSAGES CONTROL']
disable = '''
bad-continuation,
duplicate-code,
invalid-name,
line-too-long,
logging-fstring-interpolation,
missing-docstring,
no-else-return,
raise-missing-from,
too-few-public-methods,
too-many-arguments,
too-many-branches,
too-many-instance-attributes,
too-many-lines,
too-many-locals,
too-many-nested-blocks,
too-many-statements,
wrong-import-order,
unsubscriptable-object
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
