[tool.poetry]
name = "fgo-game-data-api"
version = "5.52.0"
description = "Provide raw and processed FGO game data"
authors = ["squaresmile <squaresmile@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.63.0"
uvicorn = {extras = ["standard"], version = "^0.13.4"}
python-dotenv = "^0.15.0"
fuzzywuzzy = "^0.18.0"
python-Levenshtein = "^0.12.2"
orjson = "^3.5.1"
aiofiles = "^0.6.0"
GitPython = "^3.1.14"
toml = "^0.10.2"
redis = "^3.5.3"
SQLAlchemy = {version = "1.4.0b3", extras = ["postgresql"]}
httpx = "^0.17.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pylint = "^2.7.2"
mypy = "^0.812"
black = "^20.8b1"
pytest-xdist = "^2.1.0"
coverage = "^5.5"
fuzzywuzzy-stubs = "^0.0.1"
isort = "^5.7.0"
sqlalchemy-stubs = {git = "https://github.com/squaresmile/sqlalchemy-stubs.git"}
pytest-asyncio = "^0.14.0"

[tool.isort]
line_length = 88
known_third_party = "orjson"
multi_line_output = 3
force_grid_wrap = 0
lines_after_imports = 2
combine_as_imports = true
include_trailing_comma = true

[tool.pylint.MASTER]
extension-pkg-whitelist = "orjson,pydantic"

[tool.pylint.'MESSAGES CONTROL']
disable = '''
bad-continuation,
duplicate-code,
invalid-name,
line-too-long,
logging-fstring-interpolation,
missing-docstring,
no-else-return,
raise-missing-from,
too-few-public-methods,
too-many-arguments,
too-many-branches,
too-many-instance-attributes,
too-many-lines,
too-many-locals,
too-many-nested-blocks,
too-many-statements,
wrong-import-order
'''

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:The explicit passing of coroutine objects to asyncio.wait():DeprecationWarning:starlette",
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
