[tool.poetry]
name = "fgo-game-data-api"
version = "4.7.1"
description = "Provide raw and processed FGO game data"
authors = ["squaresmile <squaresmile@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0"
uvicorn = "^0"
python-dotenv = "^0"
fuzzywuzzy = "^0"
python-Levenshtein = "^0"
orjson = "^3.0.1"
aiofiles = "^0"
gitpython = "^3.1.3"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
pylint = "^2.5.2"
mypy = "^0"
black = "^19.10b0"
pytest-xdist = "^1.32.0"
requests = "^2.23.0"
coverage = "^5.1"
fuzzywuzzy-stubs = "^0.0.1"

[tool.isort]
line_length=88
known_third_party="orjson"
multi_line_output=3
force_grid_wrap=0
lines_after_imports=2
combine_as_imports=true
include_trailing_comma=true

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
